import type { Metadata } from 'next'
import { Signika_Negative } from 'next/font/google'
import './globals.css'

const single = Signika_Negative({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={single.className}>{children}</body>
		</html>
	)
}
